
DROP TABLE CF_USERS;

CREATE TABLE CF_USERS (
	CF_HANDLE VARCHAR2(255),
	FIRST_NAME VARCHAR2(255),
	LAST_NAME VARCHAR2(255),
	RATING NUMBER,
	MAX_RATING NUMBER,
	RANK VARCHAR2(255),
	MAX_RANK VARCHAR2(255),
	TITLE_PHOTO_URL VARCHAR2(255),
	COUNTRY VARCHAR2(255)
);

ALTER TABLE CF_USERS
ADD CONSTRAINT CF_USERS_PK
		PRIMARY KEY (CF_HANDLE);


DELETE FROM CF_USERS;

SELECT * FROM CF_USERS;



