DROP TABLE CF_FOLLOWINGS;

CREATE TABLE CF_FOLLOWINGS (
	USERNAME VARCHAR2(255),
	FOLLOWING_CF_HANDLE VARCHAR2(255),
	CONSTRAINT CF_FOLLOWINGS
		PRIMARY KEY (USERNAME, FOLLOWING_CF_HANDLE)
);

ALTER TABLE CF_FOLLOWINGS
ADD CONSTRAINT CF_FOLLOWING_USERNAME_FK
	FOREIGN KEY (USERNAME)
	REFERENCES USERS (USERNAME)
;

ALTER TABLE CF_FOLLOWINGS
ADD CONSTRAINT CF_FOLLOWING_FOLLOWING_CF_HANDLE_FK
	FOREIGN KEY (FOLLOWING_CF_HANDLE)
	REFERENCES CF_USERS (CF_HANDLE)
;

SELECT * FROM CF_FOLLOWINGS;
