DROP TABLE CONTEST_PARTICIPATIONS;

CREATE TABLE CONTEST_PARTICIPATIONS (
	CF_HANDLE VARCHAR2(255),
	CONTEST_ID NUMBER,
	CONTEST_RANK NUMBER,
	OLD_RATING NUMBER,
	NEW_RATING NUMBER
);

ALTER TABLE CONTEST_PARTICIPATIONS
ADD	CONSTRAINT CONTEST_PARTICIPATIONS_PK_CF_HANDLE_CONTEST_ID
	PRIMARY KEY (CF_HANDLE, CONTEST_ID);

ALTER TABLE CONTEST_PARTICIPATIONS
ADD CONSTRAINT CONTEST_PARTICIPATIONS_CF_HANDLE_FK
	FOREIGN KEY (CF_HANDLE)
	REFERENCES CF_USERS (CF_HANDLE)
;

ALTER TABLE CONTEST_PARTICIPATIONS
ADD CONSTRAINT CONTEST_PARTICIPATIONS_CONTEST_ID_FK
	FOREIGN KEY (CONTEST_ID)
	REFERENCES CONTESTS (CONTEST_ID)
;


SELECT * FROM CONTEST_PARTICIPATIONS;



