DROP TABLE PROBLEM_LOGS;

CREATE TABLE PROBLEM_LOGS (
	USERNAME VARCHAR2(255),
	CONTEST_ID NUMBER,
	PROBLEM_INDEX VARCHAR2(10),
	PROBLEM_STATUS VARCHAR2(255),
	PERSONAL_COMMENT CLOB
);

ALTER TABLE PROBLEM_LOGS
ADD	CONSTRAINT PROBLEM_LOGS_PK
		PRIMARY KEY (USERNAME, CONTEST_ID, PROBLEM_INDEX)

ALTER TABLE PROBLEM_LOGS
ADD CONSTRAINT PROBLEM_LOGS_PROBLEM_ID_FK
	FOREIGN KEY (CONTEST_ID, PROBLEM_INDEX)
	REFERENCES PROBLEMS (CONTEST_ID, PROBLEM_INDEX)
;

ALTER TABLE PROBLEM_LOGS
DROP CONSTRAINT PROBLEM_LOGS_PROBLEM_ID_FK
;

ALTER TABLE PROBLEM_LOGS
DROP CONSTRAINT PROBLEM_LOGS_FK;

ALTER TABLE PROBLEM_LOGS
ADD CONSTRAINT PROBLEM_LOGS_USERNAME_FK
	FOREIGN KEY (USERNAME)
	REFERENCES USERS (USERNAME)
;

SELECT * FROM PROBLEM_LOGS;

DELETE FROM PROBLEM_LOGS;

INSERT INTO
PROBLEM_LOGS
VALUES ('utF', 4, 'A', 'TODO', 'THIS IS <>A COMMENT');

