DROP TABLE SUBMISSIONS;

CREATE TABLE SUBMISSIONS (
	SUBMISSION_ID NUMBER,
	CF_HANDLE VARCHAR2(255),
	CONTEST_ID NUMBER,
	PROBLEM_INDEX VARCHAR2(10),
	CREATION_TIME DATE,
	SUBMISSION_TYPE VARCHAR2(255),
	PROGRAMMING_LANG VARCHAR2(255),
	VERDICT VARCHAR2(255),
	CONSTRAINT SUBMISSIONS_PK
		PRIMARY KEY (SUBMISSION_ID)
);

ALTER TABLE SUBMISSIONS
ADD CONSTRAINT SUBMISSIONS_CF_HANDLE_FK
	FOREIGN KEY (CF_HANDLE)
	REFERENCES CF_USERS (CF_HANDLE)
;

ALTER TABLE SUBMISSIONS
DROP CONSTRAINT SUBMISSIONS_CF_HANDLE_FK
;

ALTER TABLE SUBMISSIONS
ADD CONSTRAINT SUBMISSIONS_PROBLEM_ID_FK
	FOREIGN KEY (CONTEST_ID, PROBLEM_INDEX)
	REFERENCES PROBLEMS (CONTEST_ID, PROBLEM_INDEX)
;

ALTER TABLE SUBMISSIONS
DROP CONSTRAINT SUBMISSIONS_FK
;


SELECT * FROM SUBMISSIONS;