DROP TABLE USERS;

CREATE TABLE USERS (
	USERNAME VARCHAR2(255),
	PASSWORD VARCHAR2(255) NOT NULL,
	CF_HANDLE VARCHAR2(255),
	IS_ADMIN CHAR(1) DEFAULT 'N',
	CONSTRAINT USERS_PK PRIMARY KEY (USERNAME)
);

ALTER TABLE USERS
ADD CONSTRAINT USERS_FK
	FOREIGN KEY (CF_HANDLE)
	REFERENCES CF_USERS (CF_HANDLE)
;

SELECT * FROM USERS;

DELETE FROM USERS;


INSERT INTO 
USERS (USERNAME, PASSWORD, CF_HANDLE)
VALUES ('utchchhwas', 'pass', 'utchchhwas')
;
										
										
										
										
										